### PR TITLE
Fix for Anki 2.1.41

### PR DESCRIPTION
**Pull request by hgiesel**
This is still a draft.
However because the Editor CSS for 41 is vastly different from previous versions, I need input on how it should look.

### CODE REVIEW

**Comment by AnKingMed** [comment]
Is this already supposed to work on 2.1.41? I'm not getting it to work at the moment

**Comment by hgiesel** [comment]
It should not throw any errors, but it's also not applying anything yet.

**Comment by AnKingMed** [comment]
Ah ok cool! Here's what it should look like: https://github.com/AnKingMed/Browser-Resizer/blob/master/screenshots/Editor_shrink.jpg

**Comment by hgiesel** [comment]
You can have another look now. I've made it compatible with 2.1.41-42. Adapting it to 2.1.43 might not even be necessary anymore.

**Comment by abdnh** [comment]
I assume the changes were applied by @AnKingMed in https://github.com/AnKing-VIP/Browser-Resizer/commit/e875e053283b82af44086486e368cdab255cfd2e so closing this.

**Pull request closed without merging**
